### ISSUE TITLE
End Randomseed +++++++++++++

### ISSUE THREAD

**Issue by alexandrekysli** [Hologos/hackintosh-hp-probook-650-g1#2]
Very thank Guy for your guide. I have the same computer with you but I have a problem when i try to install Mojave.
I stuck with End Randomseed +++++++++++++++++++++ message.
Sorry for my bad english Guy

**Comment by Hologos** [comment]
Hi, I did some research on Google and it seems you have to install the Clover [Installer correctly](https://www.tonymacx86.com/threads/end-randomseed-reboot.249537/).

**Comment by alexandrekysli** [comment]
thanks guy but i have already fix it.
This is a BIOS bad configuration
